jsoSchema is a schema language and validation library for javascript
data, or you coudl call it json schema, that wouldn't be wrong.

== Installation ==

We provide, in the built branch, minified version of jsoSchema for
jquery and requirejs (dojo/node):

- https://raw.github.com/segv/jsoSchema/0.9/build/raw/jquery.jsoSchema.js[jquery]
- https://raw.github.com/segv/jsoSchema/0.9/build/raw/jso/Schema[requirejs]
- https://raw.github.com/segv/jsoSchema/0.9/build/min/jquery.jsoSchema.js[jquery, minified]
- https://raw.github.com/segv/jsoSchema/0.9/build/min/jso/Schema.js[requirejs, minified]

== Introduction ==

A jsoSchema schema is an object, in particular a function, which takes
as input a javascript object (usually the result of json parsing) and
tells you if the object meets certain conditions.

It's easiest if we start with an example. Let's say we have a bunch of
people objects, and they must all have a name, which itself has to be
a string:

  Record({ name: String() });

But that's probably wrong, they probably have an address field too,
but we don't know anything about it:

  Record({ name: String(),
           address: Object() });

actually, we do, we know that the address has to be a list of strings
(what each string means we don't know nor really care about):

  Record({ name: String(),
           address: Array(String()) });

oh, wait, they have to have an age too:

  Record({ name: String(),
           address: Array(String()),
           age: Number() });

but, now that I think about it, not just any number, an integer (we
don't allow kids who really want to specify that they're 3.5 years and
not 3 years old):

  Record({ name: String(),
           address: Array(String()),
           age: Integer() });

but, let's be pedantic. It's a positive number (actually it has to be
greater than 25, since our web site sells souls, and we all know the
devil doesn't want un-ripe souls):

  Record({ name: String(),
           address: Array(String()),
           age: And(Integer(), GreaterThanEquals(25)) });

thats our first example of combining schemas (we'd use && directly if
javascript would let us override operators, but it doesn't, so we
won't). jsoSchema defines a few schema which combine other schemas:
And, Or, Every and Any (and If, but we'll ignore that for now).

However, we probably can't write that exactly, using the requirejs
build what we'd actualy have to write is:

  require([ 'jso/Schema.js' ], function (s) {
    // first define our schema:
    var schema = s.Record({ name: s.String(),
                            address: s.Array(s.String()),
                            age: s.And(s.Integer(), s.GreaterThanEquals(25)) });
    // now use it:
    doXhrCall().then(function(data) {
      if (! schema.valid(data)) {
        errorBadData();
      } else {
        ...
      }
    });
  });

== API ==

Read to code if you want all the details (the code, and not this
README, is what you're actually using, so you you should read that
anyway), but here's a, probably inaccurate, summary.

=== Value Conditions ===

Number()::
  A number (as per typeof)
String()::
  A string (as per typeof)
Boolean()::
  typeof(value) === "boolean"
OfType(typeName)::
  a check on typeof
Enum(values)::
  any one of the passed in values (as per ===), values is an array
OneOf(...values)::
Condition(function)::
  passes the value to function; if functions return true-ish (the ternary operator ?: is used) passes, otherwise fails.
Constant(value)::
  Only matches the passed in value (test with ===)

=== Objects (and Arrays) ===

Record(properties)::
HashTable()::
Object(descriptoin)::
Array(item)::
  An array where each item passes item.
Tuple(...items)::
  An array of length items where each element passes the corresponding item

=== Schema Combiners ===

Or(a,b)::
  If a passes, the Or passes, otherwise b will be tested.
Any(conditions)::
  N-argument version of Or.
And(a,b)::
  If a passes b will be tested, otherwise the And fails.
Every(conditions)::
  N-argument version of And

== Compared to JSON schema ==

http://tools.ietf.org/html/draft-zyp-json-schema-04

While jsoSchema and JSON Schema server very similar purposes, they go
about it in two very different ways. A JSON Schema is a bit of data
which is passed to a validator, along with the actual data to
validate, and the validator understands the semantics of JSON Schema
and dos what the schema says it should do given the data it has.

a jsoSchema is a block of code describing how to test if something is
valid or not.

This code vs data approach has two important consequences:

1. A JSON Schema can be represented, and transmitted and stored, as
   JSON data; a jsoSchema can not.

2. A jsoSchema can perfrom any computation that's needed; a JSON
   Schema is limited to the constraints defined in the JSON Schema
   specification.

== Defining new schemas ==

If your schema can be expressed as a singe condition on a single
value, just use the Condition schema and be done with it. Otherwise,
read on, and may God have mercy on your soul (unless you eat
continuations for breakfast, than, gutten appetite).

A jso schema is just a 3 argument function: the value to validate,
what to do if the value is valid, and what to do if the value is
invalid. 

Let's pretend, as an example, that you wanted to write the And schema
combiner, but it didn't aplreay exsit (what we'll write in this
example is equivalent to the built in And combiner). You might be
tempted to wirte this:

  function (a, b) {
    return function (value, p, f) {
      if (a(value) && b(value)) {
        p();
      } else {
        f();
      }
    }
  }

i can see where you're coming from, and i understand what's going on
in your head, but your wrong; wrong with a capital W.

what you should have written was this:

  function (a, b) {
    return function (value, p, f) {
      return a(value, 
               function() { return b(value, p, f); },
               f);
      }
    }
  }

  
The latter function says, in more or less understandable english:

Test a, if it passes then test and if B passes do what we should have
done on success, otherwise do what we should have done on failure. If
A doesn't pass, than do what we were told to do on failure.

